"""Added Column Choices to the Table Questions

Revision ID: 0c77826d0f2f
Revises: be5866888b5d
Create Date: 2026-07-05 11:29:36.298823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c77826d0f2f'
down_revision: Union[str, Sequence[str], None] = 'be5866888b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('choices', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'choices')
    # ### end Alembic commands ###
